POST http://localhost:3000/api/v1/bypass
Content-Type: application/json

{
    "formUrl":"http://url5603.blsinternational.com/ls/click?upn=u001.GaJBgDIo1Owv3jaLjoOFP6nzOLrc0O1Xeqk0-2FZWOYcjqTvOqKH8pn5CMlj6iOq-2BzoHtX24SOqhMpsMX-2F4Tbl7xmxEQsWllWb5AtwABPWUap0vPUP0uzW3iYGZogJD-2FzLEGhbHZ4VL-2FCOhCprE3100cCQP8luW-2B7i5uY4fIY5PcYy0alxTAybPZFdsTLkbPGsA8jbEVfPLejUUBbG1PaiJTsnKcO0ywI1n1BBzrV8CDzEY4OOg4Hvy0-2FPMLVU-2B8e-2Fw5MLbam6S7nsZYN8IWm2s5-2BT-2F6KApYtO0eJMdUeSos2CcMyAySsx-2BaGTVSIWFBPXQ9mdt-2FHWYb53vcNY5qNge0GE7u5xh193wF-2F0EgamHe0-3DywDM_iokptJSioas16WNY2Yf3OzeutfxjnRh-2Fac20TsniS5Pm7VlfEReIptfjwzXMUnu1j0EHVvLnwzf-2BTjFQiZmUDJdp0xcBitoxk30BoiUuJaWsXRHOgOuZ7LjJQ30VTtzsndoDCYWrLZY60bf-2B8Xf6bq1HO-2BivNRCFb8o-2BKT6UL9oqnE-2FsMu6rlE6BAK8y9pVYeaho5S2rcHqxsKUcPeAOBw-3D-3D",
    "emailToSubmit":"matarprojet@gmail.com"

}
//